### PR TITLE
Add RSS feed

### PR DESCRIPTION
**Pull request by tjvr**
Yo. This'll keep me happy, if no-one else :)

### CODE REVIEW

**Comment by nathan** [comment]
Cool! Is there a good place to put `post.description` in there?

**Comment by tjvr** [comment]
I... you're not even displaying that on the site!

**Comment by tjvr** [comment]
[RSS spec](http://cyber.law.harvard.edu/rss/rss.html) says no. If you really want it, add a `<p><em>` to the top of the `<description>`.

**Comment by nathan** [comment]
Why not put it in `description`?

**Comment by tjvr** [comment]
Putting the entire post in the RSS feed is important; myself (and many other people!) like reading posts inside their RSS reader, without visiting the site.

**Comment by nathan** [comment]
Okay, fine.

**Pull request merged**
